### ISSUE TITLE
Remove Label Free Service 

### ISSUE THREAD

**Issue by brittle123** [slazzercom/slazzer-android#1]
It's not an free service. please dont misguide others. It only let us remove background of 1 image. We have to subscribe their plans for using this service. So please remove that fake 100% free service label from this project.

**Comment by slazzercom** [comment]
Hi, 
You can processed and  download unlimited preview image from [here](https://slazzer.com).
Also download [slazzer android application ](https://play.google.com/store/apps/details?id=com.slazzer) from google play and download unlimited preview image.

Thanks
Slazzer Team
